### PR TITLE
Add lexer code

### PR DESCRIPTION
**Pull request by ameamenoame**
Add in the current lexer code.

- [x] The commit message follows our guidelines.
- For bug fixes and features:
    - [x] You tested the changes.
    - [ ] You updated the docs or changelog.

Related issue (if applicable): #10 

**What kind of change does this PR introduce?**
Just adding in the lexer code for the parser.

### CODE REVIEW

**Comment by NathanLovato** [comment]
Great work. The only change I'd request for the language would be the use of `and`, `or`, and `not` over C-style conditionals, for consistency with the rest of the language: it's intended for writers, not programmers, and everything else looks like English.

There are some things I'd rename for educational purposes, but I'll take care of that directly once you made the above change. And then it'll be good to merge, so you can move to the parser as soon as you changed these keywords.

**Comment by ameamenoame** [comment]
I've made the change to the conditionals' syntax. I'll start work on the parser now.

**Comment by NathanLovato** [comment]
I've refactored the code and added a tiny script to test the tokenizer (and eventually parser).

The most notable changes for you:

- `read_script()` now doesn't tokenize. Instead, there's a function to get a file's content, `read_file_content()`, and you have to call `tokenize()` separately.
- Changed the term `FUNCTION` to `COMMAND`, mostly so nobody can think that the language supports functions.

Besides that, I did some renaming, moving a bit of code around, and changing names, mostly for teaching purposes. 

Here are some ode style notes, guidelines I'd like you to follow:

- Please add comments on separate lines, above the line they comment.
- Use two leading dash characters for docstrings, i.e. `## `, and one for comments, i.e. `# `. This is to follow the format for Godot 4's built-in documentation generator.
- Use CONSTANT_CASE for constants. The only exception is when the constant represents a "type", typically when loading scenes like `const Weapon := preload("Weapon.tscn")` (that follows the official gdscript guidelines).
- And please mark pseudo-private functions and variables with a leading underscore. Like the DialogueScript's properties weren't meant to be accessed directly, functions like `_tokenize_comment()`, etc.

These are all part of the official style guide, it's for consistency with our projects and other Godot projects.

About naming:

- Favor explicit names for public functions and methods. In this case, mostly for the `DialogueScript`'s methods: I renamed `current` -> `get_current_character`, `previous` -> `get_previous_character`, etc. 

You can stick to shorter names for local variables, I'm even fine with one-letter names for a short loop, those kinds of things. Again, mostly for teaching purposes. Explicit names make it easier for other Godot users to understand the code.

**Comment by ameamenoame** [comment]
I've gone through your style guide too quickly it seems... I'm sorry you had to point it out for me. I'll do my best to follow the style guide going forward.

**Comment by NathanLovato** [comment]
Don't worry about that, it takes everyone a few reviews to get used to a style guide.

**Pull request merged**
